ask/ask/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qa.urls')),
]

ask/qa/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('question/<int:pk>/', views.question_details, name='question_details'),
    path('ask/', views.ask, name='ask'),
    path('popular/', views.popular, name='popular'),
    path('like/', views.like_question, name='like_question'),
]

ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-added_at')

    def popular(self):
        return self.order_by('-rating')


class Question(models.Model):
    objects = QuestionManager()
    title = models.CharField(default='', max_length=1024)
    text = models.TextField(default='')
    added_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')

    def get_url(self):
        return "/question/{}/".format(self.id)

    def __str__(self):
        return self.title


class Answer(models.Model):
    text = models.TextField(default='')
    added_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.text

ask/qa/forms.py
from django import forms
from .models import Question, Answer
from django.contrib.auth.models import User


class AskForm(forms.Form):
    title = forms.CharField(max_length=1024)
    text = forms.CharField(widget=forms.Textarea)

    def clean_title(self):
        title = self.cleaned_data['title']
        if title.strip() == '':
            raise forms.ValidationError('Title field cannot be empty')
        return title

    def clean_text(self):
        text = self.cleaned_data['text']
        if text.strip() == '':
            raise forms.ValidationError('Text field cannot be empty')
        return text

    def save(self):
        question = Question(**self.cleaned_data)
        question.author_id = self._user.id
        question.save()
        return question


class AnswerForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    question = forms.IntegerField(widget=forms.HiddenInput)

    def clean_text(self):
        text = self.cleaned_data['text']
        if text.strip() == '':
            raise forms.ValidationError('Text field cannot be empty')
        return text

    def clean_question(self):
        question_id = self.cleaned_data['question']
        try:
            question = Question.objects.get(id=question_id)
        except Question.DoesNotExist:
            raise forms.ValidationError('Question not found')
        return question

    def save(self):
        answer = Answer(**self.cleaned_data)
        answer.author_id = self._user.id
        answer.save()
        return answer


class SignupForm(forms.Form):
    username = forms.CharField(max_length=150, required=False)
    email = forms.EmailField(required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('A user with the same username already exists')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('A user with the same email already exists')
        return email

    def save(self):
        user = User.objects.create_user(**self.cleaned_data)
        user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)

ask/qa/views.py
from django.http import HttpResponseRedirect, HttpResponseServerError
from .paginations import paginate
from django.shortcuts import render, get_object_or_404, reverse
from django.views.decorators.http import require_GET
from .models import Question, Answer
from .forms import AskForm, AnswerForm, SignupForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .ajax import (HttpResponseAjax, HttpResponseAjaxError,
                   login_required_ajax)


@require_GET
def question_list(request, *args, **kwargs):
    questions = Question.objects.order_by('-id')
    paginator, page, limit = paginate(request, questions)
    context = {
        'title': 'List of New Questions',
        'questions': page,
        'paginator': paginator,
        'limit': limit,
    }
    return render(request, 'question_list.html', context)


@require_GET
def popular(request, *args, **kwargs):
    questions = Question.objects.popular()
    paginator, page, limit = paginate(request, questions)
    context = {
        'title': 'List of Popular Questions',
        'questions': page,
        'paginator': paginator,
        'limit': limit,
    }
    return render(request, 'question_list.html', context)


@login_required(login_url='/login/')
def question_details(request, pk):
    question = get_object_or_404(Question, id=pk)
    is_liked = False
    if question.likes.filter(id=request.user.id).exists():
        is_liked = True
    answers = Answer.objects.filter(question=pk).order_by('-added_at')
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            form._user = request.user
            form.save()
            url = question.get_url()
            return HttpResponseRedirect(url)
    else:
        form = AnswerForm(initial={'question': question.id})
    context = {
        'title': 'Question Page',
        'question': question,
        'answers': answers,
        'is_liked': is_liked,
        'form': form,
    }
    return render(request, 'question_detail.html', context)


@login_required(login_url='/login/')
def ask(request):
    if request.method == 'POST':
        form = AskForm(request.POST)
        if form.is_valid():
            form._user = request.user
            question = form.save()
            url = question.get_url()
            return HttpResponseRedirect(url)
    else:
        form = AskForm()
    context = {
        'title': 'Ask a Question',
        'form': form,
    }
    return render(request, 'base_form.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            form.save()
            user = authenticate(username=username,
                                password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('question_list'))
            else:
                return HttpResponseServerError()
    else:
        form = SignupForm()
    context = {
        'title': 'User registration',
        'form': form,
    }
    return render(request, 'base_form.html', context)


def log_in(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,
                                password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('question_list'))
            else:
                form.add_error(None, 'The username or password you entered is incorrect')
    else:
        form = LoginForm()
    context = {
        'title': 'Sign in',
        'form': form,
    }
    return render(request, 'base_form.html', context)


def log_out(request):
    if request.user is not None:
        logout(request)
        return HttpResponseRedirect(reverse('question_list'))


@login_required_ajax
def like_question(request):
    question = get_object_or_404(Question, id=request.POST.get('question_id'))
    is_liked = False
    if question.likes.filter(id=request.user.id).exists():
        question.likes.remove(request.user)
        question.rating -= 1
        is_liked = False
        message = 'You disliked this question'
    else:
        question.likes.add(request.user)
        question.rating += 1
        is_liked = True
        message = 'You liked this question'
    question.save()
    if question:
        return HttpResponseAjax(message=message)
    else:
        return HttpResponseAjaxError(code='bad_params',
                                     message='Question does not exist',)

ask/qa/templates/ask_question.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}{{ title }} {{ page }}
{% endblock %}
{% block content %}
{{ block.super }}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="/ask/">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group {% if field.errors %}has-error{% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

ask/qa/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Questions & Answers - {% endblock %}</title>
</head>
<body>
    {% block content %}
    <nav class="navigation">
        <a href="/">New questions</a> |
        <a href="/popular/">Popular questions</a> |
        <a href="/ask/">Ask a Question</a> |
        {% if not request.user.is_anonymous %}
            Current user:
            {{ request.user }} |
            <a href="/logout/">Log Out</a>
        {% else %}
            <a href="/signup/">Sign Up</a> |
            <a href="/login/">Log In</a>
        {% endif %}
    </nav>
    <h1>{{ title }}</h1>
    {% endblock %}
</body>
</html>

ask/qa/templates/base_form.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}{{ title }} {{ page }}
{% endblock %}
{% block content %}
{{ block.super }}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group {% if field.errors %}has-error{% endif %}">
                <label class="control-label">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

ask/qa/templates/question_detail.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}{{ title }}. {{ question.title }}
{% endblock %}
{% block content %}
{{ block.super }}
{% if question %}
<div class="question">
    <h1>Question {{ question.id }}: {{ question.title }}</h1>
    <h2>Rating: {{ question.rating }}. Author - {{ question.author.username }}. Added {{ question.added_at }}</h2>
    <p>{{ question.text }}</p>
</div>
{% endif %}
<hr>
{% if is_liked %}
    <input type="button" id="dislike" name="{{ question.id }}" value="Dislike" />
{% else %}
    <input type="button" id="like" name="{{ question.id }}" value="Like" />
{% endif %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script type="text/javascript">
    $("#dislike, #like").click(function () {
        $.ajax({
            type: "POST",
            url: "{% url 'like_question' %}",
            data: {'question_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function (response) {
                alert(response.message);
                location.reload(true);
            },
            error: function (rs, e) {
                alert(rs.responseText);
            }
        });
    })
</script>
{% if answers %}
<div class="answers">
    {% for answer in answers %}
    <div class="answer">
        <h3>Answered {{ answer.author.username }}, {{ answer.added_at }}:</h3>
        <p>{{ answer.text }}</p>
    </div>
    <hr>
    {% endfor %}
</div>
{% else %}
    <p>There are no answers to this question yet.</p>
{% endif %}
{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}
<form class="form-horizontal" method="post" action="{{ question.get_url }}">
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            <div class="control-group {% if field.errors %}has-error{% endif %}">
                {% if field.name != 'question' %}
                    <label class="control-label">{{ field.label }}</label>
                {% endif %}
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">To answer</button>
    </div>
</form>
{% endblock %}

ask/qa/templates/question_list.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}{{ title }}. Page {{ questions.number }}{{ page }}
{% endblock %}
{% block content %}
{{ block.super }}
{% if questions %}
<div class="questions">
    {% for question in questions %}
    <div class="question">
        <h3>Question {{ question.id }}: <a href="/question/{{ question.id }}/">{{ question.title }}</a></h3>
        <h5>Rating: {{ question.rating }}. Author - {{ question.author.username }}. Added {{ question.added_at }}</h5>
        <p>{{ question.text }}</p>
        {# backreference for ForeignKey #}
        {% with answers=question.answer_set.count %}
        <p>Answers: {{ answers }}</p>
        {% endwith %}
    </div>
    <hr>
    {% endfor %}
</div>
{% else %}
    <p>No questions yet.</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if questions.has_previous %}
        <a href="?page={{ questions.previous_page_number }}&limit={{ limit }}"><<</a>
        {% endif %}
        <span class="current">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}
        </span>
        {% if questions.has_next %}
        <a href="?page={{ questions.next_page_number }}&limit={{ limit }}">>></a>
        {% endif %}
    </span>
</div>
{% endblock %}